# order here is the default order we want classes in when rendered for docs
# as needed, the docs compile can locally render the list out by bit order or other attrs
[METADATA]
description = [
    "Low levels of change",
    "Two new bits; relatively high reliance on exclusions",
    "Redefine a handful of existing little-used classes",
    "Redefine spec / advice for selected classes.",
]

# cargo classes

[CC_PASSENGERS]
bit_number = 0
code = "0x0001"
nml_cargo_class_name = "CC_PASSENGERS"
name = "Passengers"
cargo_class_description = ["Passengers."]
cargo_grf_advice = ["Generally this only applies to specific Passengers cargo."]
set_food_grade_or_not = ["Do not set - not relevant.",]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Passengers"]

[CC_LIVESTOCK]
bit_number = 12
code = "0x1000"
nml_cargo_class_name = "CC_NON_POURABLE"
name = "Livestock"
cargo_class_description = [
    "Livestock.",
    "CC_NON_POURABLE really underused CABBAGE.",
    "CC_LIVESTOCK cleans up historical oddity with livestock being piece, despite there being livestock vans in base game.",
    "Vehicles that were supporting CC_NON_POURABLE are probably ok if refitting livestock.",
    "Cargos that used CC_NON_POURABLE are probably ok in livestock vehicles.",
    "This class supports other forms of livestock."
]
cargo_grf_advice = ["CABBAGE"]
set_food_grade_or_not = ["Set EXCLUDE_FOOD_GRADE.",]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Wheat", "Corn", "Maize", "Rice", "Sugar", "Cassava", "Flour", "Coffee", "Beans", "Farm Supplies", "Food"]

[CC_MAIL]
bit_number = 1
code = "0x0002"
nml_cargo_class_name = "CC_MAIL"
name = "Mail"
cargo_class_description = ["Mail."]
cargo_grf_advice = ["Generally this only applies to specific Mail cargo."]
set_food_grade_or_not = ["Recommended: set EXCLUDE_FOOD_GRADE.",]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Mail"]

[CC_EXPRESS]
bit_number = 2
code = "0x0004"
nml_cargo_class_name = "CC_EXPRESS"
name = "Express"
cargo_class_description = ["CABBAGE."]
cargo_grf_advice = ["To maximise vehicle compatiblity, consider also setting CC_PIECE_GOODS."]
set_food_grade_or_not = ["Recommended: set EXCLUDE_FOOD_GRADE.",]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["CABBAGE"]

[CC_ARMOURED]
bit_number = 3
code = "0x0008"
nml_cargo_class_name = "CC_ARMOURED"
name = "Armoured"
cargo_class_description = ["CABBAGE."]
cargo_grf_advice = ["To maximise vehicle compatiblity, consider also setting CC_EXPRESS and CC_PIECE_GOODS."]
set_food_grade_or_not = ["Recommended: set EXCLUDE_FOOD_GRADE.",]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Valuables", "Diamonds", "Gold", "Explosives"]

[CC_PIECE_GOODS]
bit_number = 5
code = "0x0020"
nml_cargo_class_name = "CC_PIECE_GOODS"
name = "Piece Goods"
cargo_class_description = [
    "Most cargos can be transported packaged in crates, boxes, barrels, jars, tins, cans, bags, sacks, bales, or pallets.",
    "This class is suitable for many cargos, including bulk, liquid, gas, powder, and food items."
]
cargo_grf_advice = [
    "This is probably the most widely supported cargo class in vehicles and should be set for many freight cargos to maximise vehicle compatibility.",
    "Each of the other freight classes has advice on combining with piece goods.",
    "Don't set for non-freight cargos like passengers and mail.",
]
set_food_grade_or_not = ["Set one or *none* of CC_EXCLUDE_FOOD_GRADE or CC_EXCLUDE_NON_FOOD_GRADE. Some packaged cargos may be suitable for both food-grade and non-food grade vehicles (potatoes, alcohol).  Some may be more clearly food-grade (fish) or non-food-grade (explosives).",]
vehicle_grf_advice = [
    "Freight vehicle GRFs: always provide vehicles supporting this class as it represents the most common class for freight cargos.",
    "Does not apply if there are no freight vehicles in the GRF."
]
example_cargos = ["Goods", "Chemicals", "Steel", "Copper", "Paper", "Logs", "Oxygen", "Tyres", "Wool", "Timber", "Building Materials", "Farm Supplies", "Glass", "Aluminium", "Zinc"]

[CC_OPEN_BULK]
bit_number = 4
code = "0x0010"
nml_cargo_class_name = "CC_BULK"
name = "Open Bulk"
cargo_class_description = ["Loose bulk cargo that will flow under gravity that do not require covering."]
cargo_grf_advice = [
    "CABBAGE",
]
set_food_grade_or_not = [
    "Recommended: Set CC_EXCLUDE_FOOD_GRADE. Most food-grade cargos will not be suitable for open bulk transport. Most bulk-open cargos will not be food grade.",
]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Coal", "Iron Ore", "Stone", "Gravel", "Sand", "Sugar Beet", "Sulphur"]

[CC_COVERED_BULK]
bit_number = 9
code = "0x0200"
nml_cargo_class_name = "CC_COVERED"
name = "Covered Bulk"
cargo_class_description = ["Bulk materials needing cover during transport.", "CABBAGE."]
cargo_grf_advice = [
    "CABBAGE",
]
set_food_grade_or_not = [
    "Recommended: Set one (not both) of CC_EXCLUDE_FOOD_GRADE or CC_EXCLUDE_NON_FOOD_GRADE.",
]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Cement", "Fertilizers", "Salt", "Potash", "Sand", "Kaolin Clay"]

[CC_LIQUID]
bit_number = 6
code = "0x0040"
nml_cargo_class_name = "CC_LIQUID"
name = "Liquid"
cargo_class_description = ["Transport of liquids."]
cargo_grf_advice = [
    "CABBAGE",
]
set_food_grade_or_not = [
    "Recommended: set one (not both) of CC_EXCLUDE_FOOD_GRADE or CC_EXCLUDE_NON_FOOD_GRADE.",
]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Crude Oil", "Petroleum Fuels", "Chemicals", "Acid", "Paints & Coatings", "Sulphur", "Coal Tar"]

[CC_GAS]
bit_number = 8
code = "0x0100"
nml_cargo_class_name = "CC_HAZARDOUS"
name = "Gas"
cargo_class_description = ["Gases, including those that may be transported under pressure or cryogenically."]
cargo_grf_advice = [
    "CABBAGE",
]
set_food_grade_or_not = [
    "Unlikely to be relevant or useful for gas cargos."
]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Nitrogen", "Ammonia", "Chlorine", "Oxygen", "Welding Supplies"]

[CC_POWDER]
bit_number = 11
code = "0x0800"
nml_cargo_class_name = "CC_POWDERIZED"
name = "Dry Powder"
cargo_class_description = ["Dry powdered materials that flow under air pressure."]
cargo_grf_advice = [
    "Set this class for all powder cargos.",
]
set_food_grade_or_not = [
    "Recommended: Set one (not both) of CC_EXCLUDE_FOOD_GRADE or CC_EXCLUDE_NON_FOOD_GRADE.",
]
vehicle_grf_advice = [
    "If specialist powder vehicles need to be separated from general powder vehicles, manage this by including or excluding specific cargo labels.",
    "For example, GRFs may provide dedicated vehicles for food-grade powders or carbon black, which should be handled with appropriate labels."
]
example_cargos = ["Cement", "Carbon Black", "Sand", "Soda Ash", "Quicklime", "Flour", "Sugar", "Cleaning Agents"]

[CC_EXCLUDE_NON_FOOD_GRADE]
bit_number = 13
code = "0x2000"
nml_cargo_class_name = "CC_EXCLUDE_NON_FOOD_GRADE"
name = "Exclude Non-Food-Grade"
cargo_class_description = ["CC_EXCLUDE_NON_FOOD_GRADE."]
cargo_grf_advice = ["CABBAGE"]
set_food_grade_or_not = ["CABBAGE",]
vehicle_grf_advice = ["CABBAGE"]
example_cargos = ["Milk", "Alcohol", "Edible Oil", "Sugar", "Molasses", "Cola", "Water"]

[CC_EXCLUDE_FOOD_GRADE]
bit_number = 14
code = "0x4000"
nml_cargo_class_name = "CC_EXCLUDE_FOOD_GRADE"
name = "Exclude Food-Grade"
cargo_class_description = ["CC_EXCLUDE_FOOD_GRADE."]
cargo_grf_advice = ["CABBAGE."]
set_food_grade_or_not = ["CABBAGE",]
vehicle_grf_advice = ["CABBAGE."]
example_cargos = ["CABBAGE."]

[CC_MISFIT]
bit_number = 10
code = "0x0400"
nml_cargo_class_name = "CC_OVERSIZED"
name = "Misfit"
cargo_class_description = [
    "Cargos that defy easy categorisation, and should be handled by label, but need to fall back to a class for vehicle grfs that aren't aware of the label.",
    "This is for cargos that really don't fit as piece goods, or as form of bulk (dry or liquid).",
    "This would include cargos that are oversized, overweight, or need very special handling."
]
cargo_grf_advice = ["CABBAGE."]
set_food_grade_or_not = [
    "Unlikely to be relevant or useful for misfit cargos."
]
vehicle_grf_advice = ["Cargo might need dedicated vehicles, by label. But sensible fallbacks might be any of: open, van, or flat vehicles."]
example_cargos = []

[CC_REFRIGERATED]
bit_number = 7
code = "0x0080"
nml_cargo_class_name = "CC_REFRIGERATED"
name = "Refrigerated"
cargo_class_description = ["Packaged food items that may require temperature control."]
cargo_grf_advice = ["Just set express, piece, food grade for cargos.", "CABBAGE."]
set_food_grade_or_not = ["CABBAGE",]
vehicle_grf_advice = ["Vehicles might want to handle this cargo for legacy reasons.", "CABBAGE exclude non-food-grade."]
example_cargos = ["CABBAGE"]
do_not_use = true

[CC_SPECIAL]
bit_number = 15
code = "0x8000"
nml_cargo_class_name = "CC_SPECIAL"
name = "Special"
cargo_class_description = ["Reserved.", "Do not use this class."]
cargo_grf_advice = [""]
set_food_grade_or_not = ["CABBAGE",]
vehicle_grf_advice = [""]
example_cargos = ["-"]
do_not_use = true


# cargo examples (non-exhaustive)

[CARGO_MILK]
name = "Milk"
cargo_description = "Milk CABBAGE"
cargo_classes = ["CC_LIQUID", "CC_EXCLUDE_NON_FOOD_GRADE"]

[CARGO_OIL]
name = "Oil"
cargo_description = "Oil CABBAGE"
cargo_classes = ["CC_LIQUID", "CC_EXCLUDE_FOOD_GRADE"]

[CARGO_GOODS]
name = "Goods"
cargo_description = "Goods CABBAGE"
cargo_classes = ["CC_PIECE_GOODS"]

[CARGO_QUICKLIME]
name = "Quicklime"
cargo_description = "Quicklime CABBAGE"
cargo_classes = ["CC_COVERED", "CC_PIECE_GOODS"]

[CARGO_PASSENGERS]
name = "Passengers"
cargo_description = "Passengers CABBAGE"
cargo_classes = ["CC_PASSENGERS"]

[CARGO_MAIL]
name = "Mail"
cargo_description = "Mail CABBAGE"
cargo_classes = ["CC_MAIL"]

[CARGO_OXYGEN]
name = "Oxygen"
cargo_description = "Oxygen CABBAGE"
cargo_classes = ["CC_GAS"]

[CARGO_SAND]
name = "Sand"
cargo_description = "Sand CABBAGE"
cargo_classes = ["CC_OPEN_BULK", "CC_COVERED_BULK"]

[CARGO_SULPHUR]
name = "Sulphur"
cargo_description = "Sulphur CABBAGE"
cargo_classes = ["CC_OPEN_BULK", "CC_COVERED_BULK"]

[CARGO_COAL]
name = "Coal"
cargo_description = "Coal CABBAGE"
cargo_classes = ["CC_OPEN_BULK"]

[CARGO_IRON_ORE]
name = "Iron Ore"
cargo_description = "Iron Ore CABBAGE"
cargo_classes = ["CC_OPEN_BULK"]

[CARGO_SCRAP_METAL]
name = "Scrap Metal"
cargo_description = "Scrap Metal CABBAGE"
cargo_classes = ["CC_OPEN_BULK"]

# vehicle examples (non-exhaustive)

[VEHICLE_CABBAGE]
name = "Cabbage Vehicle"
vehicle_description = "Cabbage Vehicle"
cargo_classes_allowed = []
cargo_classes_disallowed = []

[VEHICLE_ARMOURED_VAN]
name = "Armoured Van"
vehicle_description = "Secure vehicles for transporting valuable items."
cargo_classes_allowed = ["CC_ARMOURED"]
cargo_classes_disallowed = []

[VEHICLE_PRESSURE_TANKER]
name = "Pressure Tanker"
vehicle_description = "Vehicle for transporting gases under pressure."
cargo_classes_allowed = ["CC_GAS"]
cargo_classes_disallowed = []

[VEHICLE_HOPPER]
name = "Hopper"
vehicle_description = "Open vehicles designed for gravity loading and unloading bulk materials that don't need covering."
cargo_classes_allowed = ["CC_OPEN_BULK"]
cargo_classes_disallowed = []

[VEHICLE_COVERED_HOPPER]
name = "Covered Hopper"
vehicle_description = "CABBAGE."
cargo_classes_allowed = ["CC_COVERED_BULK"]
cargo_classes_disallowed = []

[VEHICLE_BOX_VAN]
name = "Box Van"
vehicle_description = "Cabbage."
cargo_classes_allowed = ["CC_PIECE_GOODS"]
cargo_classes_disallowed = []

[VEHICLE_FOOD_TANKER]
name = "Food Tanker"
vehicle_description = "Cabbage."
cargo_classes_allowed = ["CC_LIQUID"]
cargo_classes_disallowed = ["CC_EXCLUDE_FOOD_GRADE"]

[VEHICLE_MAIL_VAN]
name = "Mail Van"
vehicle_description = "Cabbage."
cargo_classes_allowed = ["CC_MAIL"]
cargo_classes_disallowed = []

[VEHICLE_PASSENGER_VEHICLE]
name = "Passenger Vehicle"
vehicle_description = "Cabbage."
cargo_classes_allowed = ["CC_PASSENGERS"]
cargo_classes_disallowed = []

[VEHICLE_OPEN_CARGO]
name = "Open Cargo Vehicle"
vehicle_description = "Cabbage."
cargo_classes_allowed = ["CC_PIECE_GOODS", "CC_OPEN_BULK", "CC_LIQUID"]
cargo_classes_disallowed = []


#vehicle_description = "Vehicles designed for transporting packaged food."
#vehicle_description = "Vehicles designed for flatbed transport."
#vehicle_description = "Vehicles designed for transporting powdered materials."
#vehicle_description = "Vehicles suitable for transporting passengers."
#vehicle_description = "Vehicles designed for mail transport."
#vehicle_description = "Vehicles suited for priority express delivery."
#vehicle_description = "General cargo vehicles, including flat vehicles, vehicles with sides, and vehicles with roofs."
#vehicle_description = "Vehicles designed for carrying bulk materials."
#vehicle_description = "Vehicles designed for transporting covered food-grade bulk materials."
#vehicle_description = "Vehicles suitable for transporting covered non-food bulk materials."
#vehicle_description = "Vehicles suitable for transporting non-food liquids."
#vehicle_description = "Vehicles designed for transporting food-grade liquids."
